import json
from fastapi import APIRouter, HTTPException, Body
from sqlalchemy.orm import Session
from app.db.session import SessionLocal
from app.db.models import Case, Event
from app.core.detections import detect
from app.core.scoring import score_case
from app.core.timeline import build_timeline, timeline_markdown
from app.core.summary import summarize
from app.core.iocs import extract_iocs
from app.core.graph import build_user_host_edges
from app.core.recommendations import recommend_actions, likely_happened
from app.core.rules_engine import load_rules, run_rules


router = APIRouter()

def _load_case_events(db: Session, case_id: int):
    c = db.query(Case).filter(Case.id == case_id).first()
    if not c:
        raise HTTPException(status_code=404, detail="Case not found")

    rows = db.query(Event).filter(Event.case_id == case_id).all()
    events = []
    for r in rows:
       events.append({
    "ts": r.ts,
    "host": r.host,
    "channel": r.channel,
    "event_id": r.event_id,
    "level": r.level,
    "user": r.user,
    "src_ip": r.src_ip,
    "process_name": r.process_name,
    "command_line": r.command_line,
    "parent_process": r.parent_process,
    "logon_type": r.logon_type,
    "raw": json.loads(r.raw_json),
})
    return c, events

@router.get("/{case_id}")
def get_case(case_id: int):
    db: Session = SessionLocal()
    try:
        c = db.query(Case).filter(Case.id == case_id).first()
        if not c:
            raise HTTPException(status_code=404, detail="Case not found")
        return {"id": c.id, "name": c.name, "created_at": str(c.created_at)}
    finally:
        db.close()

@router.get("/{case_id}/analyze")
def analyze_case(case_id: int):
    db: Session = SessionLocal()
    try:
        c, events = _load_case_events(db, case_id)
        dets = detect(events)

        rules, manifest, validation = load_rules("rules")
        rule_dets = run_rules(events, rules)

        # merge (dedupe by title + rule_id)
        seen = set()
        merged = []
        for d in dets + rule_dets:
            key = (d.get("title", ""), d.get("rule_id", ""))
            if key in seen:
                continue
            seen.add(key)
            merged.append(d)
        dets = merged

        score = score_case(dets, events)
        summary = summarize(dets, score, events)
        return {
            "case": {"id": c.id, "name": c.name},
            "score": score,
            "detections": dets,
            "summary": summary,
        }
    finally:
        db.close()

@router.get("/{case_id}/timeline")
def get_timeline(case_id: int, limit: int = 200):
    db: Session = SessionLocal()
    try:
        _, events = _load_case_events(db, case_id)
        return {"timeline": build_timeline(events, limit=limit)}
    finally:
        db.close()


@router.get("/{case_id}/detections")
def get_detections(case_id: int):
    db: Session = SessionLocal()
    try:
        _, events = _load_case_events(db, case_id)
        builtin = detect(events)
        rules, manifest, validation = load_rules("rules")
        by_rule = run_rules(events, rules)
        return {
            "pack": manifest.get("pack", {}),
            "rules_loaded": len(rules),
            "rules_validation": validation,
            "builtin": builtin,
            "rules": by_rule,
        }
    finally:
        db.close()

@router.get("/{case_id}/report.md")
def get_report_md(case_id: int):
    db: Session = SessionLocal()
    try:
        c, events = _load_case_events(db, case_id)
        dets = detect(events)
        rules, manifest, validation = load_rules("rules")
        rule_dets = run_rules(events, rules)

        # merge (dedupe by title + rule_id)
        seen = set()
        merged = []
        for d in dets + rule_dets:
            key = (d.get("title", ""), d.get("rule_id", ""))
            if key in seen:
                continue
            seen.add(key)
            merged.append(d)
        dets = merged

        score = score_case(dets, events)
        summary = summarize(dets, score, events)
        narrative = likely_happened(dets)
        actions = recommend_actions(dets)
        iocs = extract_iocs(events, top_n=10)
        graph = build_user_host_edges(events, top_n=20)

        md = []
        md.append(f"# DFIR Case Report: {c.name}")
        md.append(f"Case: {c.name}")
        md.append("Generated by: DFIR AI Assistant")
        md.append(f"Events Processed: {len(events)}")
        md.append(f"Detections Triggered: {len(dets)}")
        md.append("")
        md.append(f"**Risk:** {score['label']} ({score['score']}/100)")
        md.append(f"**Confidence:** {score['confidence']}")
        md.append("")
        pack = manifest.get("pack", {})
        md.append("## Rule Pack")
        md.append(f"- Name: {pack.get('name','')}")
        md.append(f"- Version: {pack.get('version','')}")
        md.append(f"- Rules loaded: {len(rules)}")
        md.append("")
        md.append("## Summary")
        md.append(summary)
        md.append("")
        md.append("## Likely Narrative")
        md.append(narrative)
        md.append("")
        md.append("## Recommended Actions")
        for a in actions:
            md.append(f"- {a}")
        md.append("")
        md.append("## Key IOCs / Artifacts")
        md.append("")
        md.append("### Top Source IPs")
        if iocs["top_src_ips"]:
            for ip, c in iocs["top_src_ips"]:
                md.append(f"- `{ip}` (seen {c} times)")
        else:
            md.append("- None")

        md.append("")
        md.append("### Top Users")
        if iocs["top_users"]:
            for u, c in iocs["top_users"]:
                md.append(f"- `{u}` (seen {c} times)")
        else:
            md.append("- None")

        md.append("")
        md.append("### Top Hosts")
        if iocs["top_hosts"]:
            for h, c in iocs["top_hosts"]:
                md.append(f"- `{h}` (seen {c} times)")
        else:
            md.append("- None")

        md.append("")
        md.append("### Top Processes")
        if iocs["top_processes"]:
            for p, c in iocs["top_processes"]:
                md.append(f"- `{p}` (seen {c} times)")
        else:
            md.append("- None")

        md.append("")
        md.append("### Notable Command Lines (sample)")
        if iocs["top_command_lines"]:
            for cl, c in iocs["top_command_lines"]:
                md.append(f"- `{cl}` (seen {c} times)")
        else:
            md.append("- None")

        md.append("")
        md.append("### URLs")
        if iocs["urls"]:
            for url, c in iocs["urls"]:
                md.append(f"- `{url}` (seen {c} times)")
        else:
            md.append("- None")

        md.append("")
        md.append("## Activity Graph (User \u2192 Host)")
        md.append("")
        md.append(f"- Unique users: {graph['unique_users']}")
        md.append(f"- Unique hosts: {graph['unique_hosts']}")
        md.append("")
        md.append("| User | Host | Count |")
        md.append("|---|---|---:|")
        for edge in graph["edges"]:
            md.append(f"| `{edge['user']}` | `{edge['host']}` | {edge['count']} |")

        md.append("")
        md.append("## Detections")
        if not dets:
            md.append("- None")
        else:
            for d in dets:
                md.append(f"- **{d['severity'].upper()}**: {d['title']}")
                rid = d.get("rule_id")
                if rid:
                    md.append(f"  - Rule: `{rid}`")
                if d.get("mitre"):
                    tags = ", ".join([f"{t['technique']} ({t['name']})" for t in d["mitre"]])
                    md.append(f"  - MITRE: {tags}")
                md.append(f"  - Evidence events: {len(d.get('evidence_events', []))}")
                # Show the 3 most useful evidence lines
                evs = d.get("evidence_events", [])[:3]
                for ev in evs:
                    cl = ev.get("command_line", "")
                    extra = ""
                    if cl:
                        extra = f" | cmd=`{cl}`"
                    md.append(
                        f"  - Evidence: ts={ev.get('ts','')} host={ev.get('host','')} "
                        f"event_id={ev.get('event_id','')} user={ev.get('user','')} "
                        f"src_ip={ev.get('src_ip','')}{extra}"
                    )
        md.append("")
        md.append(timeline_markdown(events, limit=120))

        return "\n".join(md)
    finally:
        db.close()


@router.get("/{case_id}/iocs")
def get_iocs(case_id: int, top_n: int = 10):
    db: Session = SessionLocal()
    try:
        _, events = _load_case_events(db, case_id)
        return extract_iocs(events, top_n=top_n)
    finally:
        db.close()

@router.get("/{case_id}/graph")
def get_graph(case_id: int, top_n: int = 30):
    db: Session = SessionLocal()
    try:
        _, events = _load_case_events(db, case_id)
        return build_user_host_edges(events, top_n=top_n)
    finally:
        db.close()


@router.post("/{case_id}/status")
def set_case_status(case_id: int, status: str = Body(..., embed=True)):
    allowed = {"Open", "In Progress", "Resolved"}
    if status not in allowed:
        raise HTTPException(status_code=400, detail=f"Invalid status. Allowed: {sorted(list(allowed))}")

    db: Session = SessionLocal()
    try:
        c = db.query(Case).filter(Case.id == case_id).first()
        if not c:
            raise HTTPException(status_code=404, detail="Case not found")

        c.status = status
        db.commit()
        db.refresh(c)

        return {"id": c.id, "name": c.name, "status": c.status}
    finally:
        db.close()